version: "3.8"
services:
  vue2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue2-app
    ports:
      - "8787:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
