services:
  vue2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue2-app
    ports:
      - "8787:8080"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
